refactor: standardize CLI error reporting across executables (#306)

diff --git a/src/coremods/COREMOD_memory/scripts/milk-rmshmim b/src/coremods/COREMOD_memory/scripts/milk-rmshmim
--- a/src/coremods/COREMOD_memory/scripts/milk-rmshmim
+++ b/src/coremods/COREMOD_memory/scripts/milk-rmshmim
@@ -61,8 +61,9 @@ while getopts :h FLAG; do
             exit
             ;;
         \?)
-            echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
+            echo -e "\n\033[1;31mERROR\033[0m Option -${OPTARG} not allowed."
             printHELP
+            exit 1
             ;;
     esac
 done
@@ -73,10 +74,10 @@ shift $((OPTIND-1))
 
 if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
     if [ "$#" -ne $NBARGS ]; then
-        echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
+        echo -e "\n\033[1;31mERROR\033[0m Illegal number of parameters ($NBARGS params required, $# entered)"
     fi
     printHELP
-    exit
+    exit 1
 fi
 
 IFS=',' read -r -a array <<< "$1"
diff --git a/src/coremods/COREMOD_memory/scripts/milk-shmimlog b/src/coremods/COREMOD_memory/scripts/milk-shmimlog
--- a/src/coremods/COREMOD_memory/scripts/milk-shmimlog
+++ b/src/coremods/COREMOD_memory/scripts/milk-shmimlog
@@ -101,8 +101,9 @@ while getopts :hc: FLAG; do
             CPUset="$OPTARG"
             ;;
         \?) #unrecognized option - show help
-            echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
+            echo -e "\n\033[1;31mERROR\033[0m Option -${OPTARG} not allowed."
             printHELP
+            exit 1
             ;;
     esac
 done
@@ -111,10 +112,10 @@ shift $((OPTIND-1))
 
 if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
     if [ "$#" -ne $NBARGS ]; then
-        echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
+        echo -e "\n\033[1;31mERROR\033[0m Illegal number of parameters ($NBARGS params required, $# entered)"
     fi
     printHELP
-    exit
+    exit 1
 fi
 
 # ======================= CHECK REQUIRED FILES =================================
