added error checking to scripts

diff --git a/scripts/milk-argparse b/scripts/milk-argparse
--- a/scripts/milk-argparse
+++ b/scripts/milk-argparse
@@ -148,11 +148,15 @@ function printHELP {
     done
 
     argliststring=""
-    argindex=0
-    while [ $argindex -lt ${NBarg} ]; do
-        argliststring="${argliststring} ${inputMSargnameARRAY[$argindex]}"
-        let argindex+=1
-    done
+    if [ $MILK_SCRIPT_ARGPARSE = 1 ]; then
+		argindex=0
+		while [ $argindex -lt ${NBarg} ]; do
+			argliststring="${argliststring} ${inputMSargnameARRAY[$argindex]}"
+			let argindex+=1
+		done
+	else
+		argliststring="<argument sting>"
+	fi
 
 
     echo "------------------------------------------------------------------------"
@@ -172,11 +176,15 @@ function printHELP {
     echo "     option(s): ${optlistshort}"
     echo ""
     echo " $(tput bold)ARGUMENTS:$(tput sgr0)"
-    argindex=0
-    while [ $argindex -lt ${NBarg} ]; do
-        printf "  %12s [%s]\n     %s\n" "${fgYellow}${inputMSargnameARRAY[$argindex]}${txReset}" "${fgGreen}${inputMSargtypeARRAY[$argindex]}${txReset}" "${inputMSargdescrARRAY[$argindex]}"
-        let argindex+=1
-    done
+    if [ $MILK_SCRIPT_ARGPARSE = 1 ]; then
+		argindex=0
+		while [ $argindex -lt ${NBarg} ]; do
+			printf "  %12s [%s]\n     %s\n" "${fgYellow}${inputMSargnameARRAY[$argindex]}${txReset}" "${fgGreen}${inputMSargtypeARRAY[$argindex]}${txReset}" "${inputMSargdescrARRAY[$argindex]}"
+			let argindex+=1
+		done
+	else
+		echo "	no argument parsing"
+	fi
     echo ""
     echo " $(tput bold)OPTIONS:$(tput sgr0)"
     optindex=0
@@ -186,7 +194,7 @@ function printHELP {
         let optindex+=1
     done
     echo ""
-    exit
+    exit 0
 }
 
 
@@ -194,7 +202,7 @@ function printHELP {
 printHELPshort ()
 {
     printf "%20s       ${MSdescr}\n" "$0"
-    exit
+    exit 0
 }
 
 
@@ -234,7 +242,7 @@ function checkallprerequisites()
 function checkallprerequisitesExit()
 {
     checkallprerequisites
-    exit
+    exit 0
 }
 
 
@@ -254,19 +262,20 @@ inputMSargtypeARRAY=( )
 inputMSargdescrARRAY=( )
 
 NBarg=0
-if (( ${#MSarg[@]} )); then
-for argdat in "${MSarg[@]}";do
-    #echo "Argument ${NBarg}: $argdat"
-    IFS=':' read -r -a argarray <<< "$argdat"
-    inputMSargnameARRAY+=( ${argarray[0]} )
-    inputMSargtypeARRAY+=( ${argarray[1]} )
-    inputMSargdescrARRAY+=( "${argarray[2]}" )
-    #echo "    ${inputMSargnameARRAY[$NBarg]}"
-    let NBarg+=1
-done
-fi
+if [ $MILK_SCRIPT_ARGPARSE = 1 ]; then
+	if (( ${#MSarg[@]} )); then
+	for argdat in "${MSarg[@]}";do
+		#echo "Argument ${NBarg}: $argdat"
+		IFS=':' read -r -a argarray <<< "$argdat"
+		inputMSargnameARRAY+=( ${argarray[0]} )
+		inputMSargtypeARRAY+=( ${argarray[1]} )
+		inputMSargdescrARRAY+=( "${argarray[2]}" )
+		#echo "    ${inputMSargnameARRAY[$NBarg]}"
+		let NBarg+=1
+	done
+	fi
 #echo "NBarg = ${NBarg}"
-
+fi
 
 
 
@@ -389,44 +398,25 @@ fi
 
 checkallprerequisites
 
+if [ $MILK_SCRIPT_ARGPARSE = 1 ]; then
+	NBargin=0
+	#for MSarg in "${inputMSargARRAY[@]}";do
+	if (( ${#inputParamString[@]} )); then
+		for MSarg in "${inputParamString[@]}";do
+			#  echo "   input argument ${NBargin} : $MSarg"
+			let NBargin+=1
+		done
+	fi
 
-NBargin=0
-#for MSarg in "${inputMSargARRAY[@]}";do
-if (( ${#inputParamString[@]} )); then
-for MSarg in "${inputParamString[@]}";do
-    #  echo "   input argument ${NBargin} : $MSarg"
-    let NBargin+=1
-done
+	if [[ ${NBargin} -ne ${NBarg} ]]; then
+		echo "${fgRed} ERROR: ${NBarg} arguments expected, ${NBargin} entered ${txReset}"
+		exit 1
+	fi
 fi
 
-if [[ ${NBargin} -ne ${NBarg} ]]; then
-    echo "${fgRed} ERROR: ${NBarg} arguments expected, ${NBargin} entered ${txReset}"
-    exit
-fi
-
-
-
-
-
-function cleanup()
-{
-    echo ""
-    # optional custom cleanup provided by application
-    customcleanup
-    echo "Exiting script ${pname}"
-    echo ""
-}
-
-function settrap()
-{
-    trap cleanup EXIT
-}
-
-# call settrap function
-settrap
 
 if [ ${EXITSTATUS} = 1 ]; then
-exit
+	exit 1
 fi
 
 # log command
diff --git a/scripts/milk-script-std-config b/scripts/milk-script-std-config
--- a/scripts/milk-script-std-config
+++ b/scripts/milk-script-std-config
@@ -1,54 +1,7 @@
 #!/usr/bin/env bash
 
-MILKSCRIPTMODE=""
-if [ "$#" -ge 1 ]; then
 
-	# Print one line help and exit
-	if [ "$1" = "-hs" ]; then
-		printf "%s\n" "${MSdescr}"
-	exit
-	fi
-
-	if [ "$1" = "-h" ]; then
-		MILKSCRIPTMODE="help"
-	fi
-
-fi
-
-
-
-
-# ======================= PROCESS NAME =================================
-pnamefull=`echo "$0" | sed "s/\.\///g"`
-pname=${pnamefull##*/} 
-
-# Attempt to use undefined variable outputs error message, and forces an exit
-set -o nounset
-set -o errexit
-set -o pipefail
-
-
-function customcleanup()
-{
-	echo ""
-    #echo "default cleanup"
-}
-
-function milkdatestring()
-{
-	# ISO 8601 compliant date string
-	# UNIX time
-	date -u +'%Y-%m-%dT%H:%M:%S.%6NZ %s.%6N'
-}
-
-milkcmdstring="$(basename $0) $@"
-
-
-function milkscriptcmdlog()
-{
-	echo "$(milkdatestring) CMD ${USER}@$(pwd) ${milkcmdstring}" >> milkscriptcmd.log
-}
-
+MILK_SCRIPT_ARGPARSE=1
 
 # background color using ANSI escape
 
@@ -91,6 +44,77 @@ txReverse=$(tput rev)    # reverse
 txStandout=$(tput smso)   # standout
 txEndStand=$(tput rmso)   # exit standout
 txReset=$(tput sgr0)   # reset attributes
+
+
+
+MILKSCRIPTMODE=""
+if [ "$#" -ge 1 ]; then
+
+	# Print one line help and exit
+	if [ "$1" = "-hs" ]; then
+		printf "%s\n" "${MSdescr}"
+	exit 0
+	fi
+
+	if [ "$1" = "-h" ]; then
+		MILKSCRIPTMODE="help"
+	fi
+
+fi
+
+
+
+
+# ======================= PROCESS NAME =================================
+pnamefull=`echo "$0" | sed "s/\.\///g"`
+pname=${pnamefull##*/} 
+
+# Attempt to use undefined variable outputs error message, and forces an exit
+set -o nounset
+set -o errexit
+set -o pipefail
+
+
+
+set -eE -o functrace
+failure() {
+  local lineno=$1
+  local msg=$2
+  echo "SCRIPT $0 ${bgRed}${fgBWhite}${txBold} Failed ${txReset} at line $lineno: $msg"
+}
+trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
+
+onexitfunc() {
+	local exitcode=$?
+	if [ $exitcode = 0 ]; then
+		echo "SCRIPT $0 ${bgGreen}${fgBLack}${txBold} Success ${txReset}"
+	else
+		echo "SCRIPT $0 ${bgRed}${fgBWhite}${txBold} EXIT CODE $exitcode ${txReset}"
+		#echo "SCRIPT $0 ${bgGreen}${fgBLack}${txBold} Success ${txReset} CODE: $?"
+	fi
+}
+trap 'onexitfunc' EXIT
+
+
+
+
+function milkdatestring()
+{
+	# ISO 8601 compliant date string
+	# UNIX time
+	date -u +'%Y-%m-%dT%H:%M:%S.%6NZ %s.%6N'
+}
+
+milkcmdstring="$(basename $0) $@"
+
+
+function milkscriptcmdlog()
+{
+	echo "$(milkdatestring) CMD ${USER}@$(pwd) ${milkcmdstring}" >> milkscriptcmd.log
+}
+
+
+
 
 
 
